core/urls.py
from unicodedata import name
from django.urls import path

from core import views

urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup'
    )
]

leads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_site'),
    path(
        '',
        include(('panel.urls', 'panel'), namespace='panel')
    ),
]

panel/urls.py
from django.urls import path, include, re_path

from panel import views

urlpatterns = [
    path(
        'leads/',
        include(('lead.urls', 'lead'), namespace='lead')
    ),
    path(
        'site/',
        include(('core.urls', 'site'), namespace='site')
    ),
]

urlpatterns += [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
]

panel/views/base.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from lead.models import Leads
from lead import filters

#Mixins
from core.mixins import FilterMixin

class IndexView(LoginRequiredMixin, FilterMixin, ListView):
    model = Leads
    template_name = 'panel/index.html'
    paginate_by = 20
    filterset_class = filters.MyLeadsFilterSet
    queryset = Leads.objects.all().order_by('?') #Use '?' will make de performance more slow.

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

panel/templates/panel/navbar/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	
	<a class="navbar-brand" href="#">Welcome {{ user.username }}</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
	{% if user.is_authenticated %}
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	  <ul class="navbar-nav mr-auto">
		<li class="nav-item active">
		  <a class="nav-link" href="{% url 'panel:index'%}">Home <i class="fas fa-home"></i></a>
		</li>
		<li class="nav-item">
		  <a class="nav-link" href="{% url 'panel:lead:lead_my_list'%}">My Leads <i class="fas fa-poll-h"></i></a>
		</li>
		<li class="nav-item dropdown">
		  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Options
		  </a>
		  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			{% if user.is_staff or user.is_superuser %}
			<a class="dropdown-item" href="{% url 'panel:lead:lead_uploader'%}">Upload Leads <i class="fas fa-file-upload"></i></a>
			{% endif %}
			<a class="dropdown-item" href="{% url 'panel:lead:invoices_my_list'%}">Invoices <i class="fas fa-file-invoice"></i></a>
			<div class="dropdown-divider"></div>
			<a class="dropdown-item" href="#">Something else here</a>
		  </div>
		</li>
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			  Settings
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
			  {% if user.is_staff or user.is_superuser %}
			  <a class="dropdown-item" href="admin/">Admin <i class="fas fa-users-cog"></i></a>
			  {% endif %}
			  <a class="dropdown-item" href="#">Another action</a>
			  <div class="dropdown-divider"></div>
			  <a class="dropdown-item" href="#">Something else here</a>
			</div>
		  </li>
		<li class="nav-item">
		  <a class="nav-link" href="{% url 'panel:site:logout'%}">Logout <i class="fas fa-sign-out-alt"></i></i>
		  </a>
		</li>
	  </ul>
	  
	  <li style="float: right;">Your Balance: {{ user.my_credits }} <i class="fas fa-coins"> </i> </li>    
	</div>
	{%endif%}
  </nav>